name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: devops-ynov-lucas
  CLUSTER_NAME: cluster-devops-lucas
  CLUSTER_ZONE: europe-west3-a
  IMAGE_NAME: gcr.io/devops-ynov-lucas/vue-cloudrun

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }} # clé JSON stockée en secret GitHub
        export_default_credentials: true

    - name: Configure Docker for GCR
      run: |
        gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME:$GITHUB_SHA .
        docker push $IMAGE_NAME:$GITHUB_SHA

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME --zone $CLUSTER_ZONE

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/vue-app vue-app=$IMAGE_NAME:$GITHUB_SHA --record
        kubectl rollout status deployment/vue-app
